In [2]:
import numpy as np

# Arrays

* homogenous grid
* indexed by a tuple of non-negative integers
* __rank__: number of dimensions
* __shape__: tuple of integers that expresses size along each dimension

In [4]:
a = np.array([1, 2, 3]) # create rank 1 array

print(a)

print(type(a)) # prints "<class 'numpy.ndarray'>"
print(a.shape) # prints "(3,)"

a[0] = 4 # change element of array

print(a)

###

b = np.array([[1, 2, 3], [4, 5, 6]]) # create rank 2 array

print(b.shape) # prints "(2, 3)"

print(b[0, 1])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
[4 2 3]
(2, 3)
2


In [5]:
a = np.zeros((2, 2)) # create array of all zeros
print(a)

b = np.ones((1, 2)) # create array of all ones
print(b)

c = np.full((2, 2), 7) # create constant array with value 7
print(c)

d = np.eye(2) # create 2x2 identity matrix
print(d)

e = np.random.random((2, 2)) # create array of random values
print(e)

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.58135223  0.24986324]
 [ 0.52304078  0.27303563]]


## Array Indexing

### Slicing: 

* specify a slice for each dimension of the array
* slice of an array is a view into the same data; modifying a slice changes the original array

In [12]:
a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

b = a[:2, 1:3]

print(a[0, 1])
b[0, 0] = 77 # also affects array a
print(a[0, 1])

2
77


* mixing integer indexing with slice indexing will yield an array of __lower rank__
* using only slices yields an array of the __same rank__

In [15]:
a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])

# row views

row_r1 = a[1, :] # rank 1 view of second row of a
row_r2 = a[1:2, :] # rank 2 view of second row of a

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# column views

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing

* allows you to construct arbitrary arrays using data from another array

In [17]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# integer array indexing
# returned array has shape (3,)
print(a[[0, 1, 2], [0, 1, 0]]) # first is row index, second is col index

# equivalent to the line above
print(np.array(a[0, 0], a[1, 1], a[2, 0]))

[1 4 5]


* may select / mutate one element from each row of a matrix

In [19]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
print(a)

b = np.array([0, 2, 0, 1]) # array of indices

# select one element from each row of a with indices in b
print(a[np.arange(4), b]) # arange: return evenly spaced values within a given interval in [start, stop)

# mutate one element from each row of a with indices in b
a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing

* lets you pick elements of array that satisfy some condition

In [21]:
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

bool_idx = (a > 2) # True if elements of a that are bigger than 2, False otherwise
print(bool_idx)

print(a[bool_idx]) # pick elements of a that are bigger than 2

# equivalent to all above
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Datatypes

* Numpy tries to guess a datatype when you create an array
* functions that construct arrays usually also include an optional argument to explicitly specify the datatype

In [23]:
x = np.array([1, 2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int64
float64
int64


## Array math

* basic math functions operate element-wise on arrays
* available both as operator overloads and functions

In [24]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))

print(x ** 0.5)
print(np.sqrt(x))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


* note the difference: 
    * __*__: elementwise multiplication
    * __dot__: inner product of vectors, multiply matrix with matrix/vector

In [26]:
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[9, 10],
              [11, 12]])

v = np.array([9, 10])
w = np.array([11, 12])

# inner product
print(v.dot(w))
print(np.dot(v, w))

# matrix / vector product; produces rank 1 array
print(x.dot(v))
print(np.dot(x, v))

# matrix / matrix product; produces rank 2 array
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[31 34]
 [71 78]]
[[31 34]
 [71 78]]


* __sum__: useful to perform sum across different dimensions of an array

In [27]:
x = np.array([[1, 2],
              [3, 4]])

print(np.sum(x)) # sum all elements
print(np.sum(x, axis=0)) # sum each column
print(np.sum(x, axis=1)) # sum each row

10
[4 6]
[3 7]


* __T__: attribute that gives the transpose of a matrix

In [28]:
x = np.array([[1, 2],
              [3, 4]])

print(x)
print(x.T)

# taking the transpose of a rank 1 array does nothing
v = np.array([1, 2, 3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting

* helps automatically reshape arrays of different shapes when performing arithmetic operations to match each other

In [ ]:
x = np.array([1, 2, 3],
             [4, 5, 6],
             [7, 8, 9],
             [10, 11, 12])